# Generated by Django 6.0.4 on 2026-04-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_resena_options_resena_aprobado_resena_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/'),
        ),
        migrations.AddField(
            model_name='variante',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/'),
        ),
        migrations.AddField(
            model_name='variante',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/'),
        ),
        migrations.AddField(
            model_name='variante',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/'),
        ),
    ]
